/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.jni.de.cib.pdf;

public class CibPdfModuleJobInterface {
  protected transient boolean swigCMemOwn;
  private transient long swigCPtr;

  protected CibPdfModuleJobInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public CibPdfModuleJobInterface() {
    this(pdfModuleJNI.new_CibPdfModuleJobInterface(), true);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pdfModuleJNI.delete_CibPdfModuleJobInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProperty(String key, String value) {
    pdfModuleJNI.CibPdfModuleJobInterface_setProperty(swigCPtr, this, key, value);
  }

  public String getProperty(String str) {
    return pdfModuleJNI.CibPdfModuleJobInterface_getProperty(swigCPtr, this, str);
  }

  public long execute() {
    return pdfModuleJNI.CibPdfModuleJobInterface_execute(swigCPtr, this);
  }

  public long getJobHandle() {
    return pdfModuleJNI.CibPdfModuleJobInterface_getJobHandle(swigCPtr, this);
  }

  public String getVersionText() {
    return pdfModuleJNI.CibPdfModuleJobInterface_getVersionText(swigCPtr, this);
  }

  public String getErrorText() {
    return pdfModuleJNI.CibPdfModuleJobInterface_getErrorText(swigCPtr, this);
  }


}
