/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.jni.de.cib.pdf;

public class pdfModuleJNI
{
  public static native long new_CibPdfModuleJobInterface();
  public static native void delete_CibPdfModuleJobInterface(long job);
  public static native void CibPdfModuleJobInterface_setProperty(long job, CibPdfModuleJobInterface jobInterface, String name, String value);
  public static native String CibPdfModuleJobInterface_getProperty(long job, CibPdfModuleJobInterface jobInterface, String name);
  public static native long CibPdfModuleJobInterface_execute(long job, CibPdfModuleJobInterface jobInterface);
  public static native long CibPdfModuleJobInterface_getJobHandle(long job, CibPdfModuleJobInterface jobInterface);
  public static native String CibPdfModuleJobInterface_getVersionText(long job, CibPdfModuleJobInterface jobInterface);
  public static native String CibPdfModuleJobInterface_getErrorText(long job, CibPdfModuleJobInterface jobInterface);
  
}

